config/routes.rb
HowToTeach::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :friendships do
    get 'accept', as: 'accept'
  end

  resources :methodologies, except: :index do
    get 'paginate_comments', on: :collection
    resources :comments
  end

  root to: 'static_pages#index'
  get 'users/my_profile' => 'users#my_profile', as: 'my_profile'
  get 'users/profile/:id' => 'users#profile', as: 'profile'
  get 'users/search' => 'users#search', as: 'search'
  get 'users/paginate_feeds' => 'users#paginate_feeds'
  get 'users/paginate_friends' => 'users#paginate_friends'

  devise_for :users, controllers: { registrations: 'users/registrations' }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:manage], Methodology, user_id: user.id
    can [:read], Methodology
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :user
  belongs_to :methodology
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user

  def after_initialize message
    self.message = message
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  validate :cant_add_yourself

  def cant_add_yourself
    if user_id == friend_id
      errors.add(:friend_id, "Você não pode adicionar a si mesmo")
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :methodology

  has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: {content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"]},
                                size: { :in => 0..300.kilobytes }
end

app/models/methodology.rb
class Methodology < ActiveRecord::Base
  letsrate_rateable "qualidade"

	belongs_to :user

	validates :title, presence: true
  validates :teaser, presence: true
	validates :content, presence: true

	scope :by_user, lambda{|user| where(user_id: user.id)}

  belongs_to :user
  has_many :comments
  has_many :images
  accepts_nested_attributes_for :images, 
                                :reject_if => proc { |att| att['image'].blank? },
                                :allow_destroy => true
  has_many :videos
  accepts_nested_attributes_for :videos, 
                                :reject_if => proc { |att| att['url'].blank? },
                                :allow_destroy => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  letsrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.search(search)
    Methodology.joins('LEFT JOIN users AS u 
                          ON u.id = methodologies.user_id 
                       LEFT JOIN rating_caches as r 
                          ON methodologies.id = r.cacheable_id').where('u.first_name LIKE :search 
                          OR u.last_name LIKE :search 
                          OR methodologies.title LIKE :search', search: "%#{search}%").order('r.avg DESC') if search
  end

  has_attached_file :avatar, styles: { :profile => "100x100>", :search_thumb => "30x30>" }, 
                              default_url: "avatar-blank-:style.jpg"
  validates_attachment :avatar, content_type: {content_type: ["image/jpg", "image/gif", "image/png"]},
                                size: { :in => 0..200.kilobytes }

  has_many :methodologies, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :comments
  has_many :feeds
  has_many :schools
  accepts_nested_attributes_for :schools, 
                                :reject_if => proc { |att| att['name'].blank? },
                                :allow_destroy => true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.post_feed(user, message)
    if user.friends
      user.friends.each do |friend|
        feed = Feed.new message: message
        friend.feeds << feed
        friend.save
      end
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :methodology
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @methodology = Methodology.find(params[:methodology_id])
    @comment = @methodology.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      User.post_feed(current_user, "#{current_user.full_name} postou um comentário na metodologia #{@methodology.title}")
      redirect_to methodology_path(@methodology), notice: "Comentário adicionado com sucesso."
    else
      redirect_to methodology_path(@methodology), alert: "Comentário não foi adicionado com sucesso."
    end
    
  end

  def destroy
    @methodology = Methodology.find(params[:methodology_id])
    @comment = @methodology.comments.find(params[:id])
    @comment.destroy
    redirect_to methodology_path(@methodology_path), notice: "Comentário excluído."
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :methodology_id, :content)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def my_profile
    search_path params[:search] if params[:search]
    @user = User.find(current_user.id)
    @feeds = @user.feeds.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    @friendships = @user.friendships.order(accepted: :asc).paginate(page: params[:page], per_page: 10)
  end

  def profile
    search_path params[:search] if params[:search]
    @user = User.find(params[:id])
    @friendships = @user.friendships.paginate(page: params[:page], per_page: 10)
  end

  def paginate_feeds
    @feeds = current_user.feeds.paginate(page: params[:page], per_page: 10)
    data = []
    @feeds.each do |feed|
      hash = {}
      hash[:id] = feed.user.id
      hash[:name] = feed.user.full_name
      hash[:message] = feed.message
      data << hash
    end
    respond_to do |format|
      format.json { render json: data }
    end
  end

  def paginate_friends
    @friendships = current_user.friendships.paginate(page: params[:page], per_page: 10)
    data = []
    @friendships.each do |friendship|
      hash = {}
      hash[:id] = friendship.id
      hash[:friend_id] = friendship.friend.id
      hash[:name] = friendship.friend.full_name
      data << hash
    end
    respond_to do |format|
      format.json { render json: data }
    end
  end

  private

    def search_path(search)
      @search = User.search(search).paginate(page: params[:page], per_page: 10)
      render "search"
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/methodologies_helper.rb
module MethodologiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowToTeach</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'menu/menu' %>
  <div id="flashes">
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:error] || flash[:errors] || flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:error] || flash[:errors] || flash[:alert]  %>
        </div>
      <% end %>

      <% flash[:error] = flash[:errors] = flash[:notice] = nil %>
    </div>
  </div>
	<div class="container">
    <%= yield :javascript_includes %> 
		<%= yield %>
	</div>
</body>
</html>

app/views/menu/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/users/my_profile">How to Teach</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Meu perfil", my_profile_path %></li>
        <li><%= link_to "Nova Metodologia", new_methodology_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <%= form_tag search_path, method: 'get', class: "form-group" do %>
          <%= text_field_tag :search, params[:search], class: "navbar-search" %>&nbsp;
          <%= submit_tag "Search", class: "btn btn-primary", name: nil %>
        <% end %>
      </form>
      <div class="login-box">
        <% if user_signed_in? %>
          Logado como <strong><%= current_user.email %></strong>.
          <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_friends.html.erb
<% @friendships.each do |friendship| %>
  <p>
    <% if friendship.invited && !friendship.accepted %>
      <%= friendship.friend.first_name %> adicionou você como amigo, deseja aceitar? - 
      <%= link_to "Aceitar", friendship_accept_path(friendship, friend_id: friendship.friend.id), class: "btn btn-primary" %>
    <% elsif friendship.accepted %>
      <%= link_to "#{friendship.friend.first_name}", profile_path(friendship.friend) %> - 
      <%= link_to "Remover amigo", friendship, method: :delete, data: {confirm: "Tem certeza que deseja remover amigo?"} %>
    <% end %>
  </p>
<% end %>

app/views/shared/_methodologies.html.erb
<div class="methodology">
  <% if @user.methodologies.empty? %>
    <p>Não há metodologias cadastradas.</p>
  <% else %>
    <% @user.methodologies.each do |methodology| %>
      <h3><%= link_to "#{methodology.title}", methodology_path(methodology) %></h3>
      <p><%= rating_for methodology, "qualidade", star: 5 %></p>
      <p>
        <%= methodology.teaser %>
      </p>
      <% if current_user == @user %>
        <p>
          <%= link_to "Editar", edit_methodology_path(methodology), class: "btn btn-primary"  %>
          <%= link_to 'Remover', methodology, class: "btn btn-danger", data: {confirm: 'Você tem certeza?'}, method: :delete %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</div>