config/routes.rb
HowToTeach::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :friendships do
    get 'accept', as: 'accept'
  end

  resources :methodologies, except: :index do
    get 'paginate_comments', on: :collection
    resources :comments
  end

  root to: 'static_pages#index'
  get 'users/my_profile' => 'users#my_profile', as: 'my_profile'
  get 'users/profile/:id' => 'users#profile', as: 'profile'
  get 'users/search' => 'users#search', as: 'search'
  get 'users/paginate_feeds' => 'users#paginate_feeds'
  get 'users/paginate_friends' => 'users#paginate_friends'

  devise_for :users, controllers: { registrations: 'users/registrations' }

end

app/models/user.rb
class User < ActiveRecord::Base
  letsrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.search(search)
    Methodology.joins('LEFT JOIN users AS u 
                          ON u.id = methodologies.user_id 
                       LEFT JOIN rating_caches as r 
                          ON methodologies.id = r.cacheable_id').where('u.first_name LIKE :search 
                          OR u.last_name LIKE :search 
                          OR methodologies.title LIKE :search', search: "%#{search}%").order('r.avg DESC') if search
  end

  has_attached_file :avatar, styles: { :profile => "100x100>", :search_thumb => "30x30>" }, 
                              default_url: "avatar-blank-:style.jpg"
  validates_attachment :avatar, content_type: {content_type: ["image/jpg", "image/gif", "image/png"]},
                                size: { :in => 0..200.kilobytes }

  has_many :methodologies, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :comments
  has_many :feeds
  has_many :schools
  accepts_nested_attributes_for :schools, 
                                :reject_if => proc { |att| att['name'].blank? },
                                :allow_destroy => true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.post_feed(user, message)
    if user.friends
      user.friends.each do |friend|
        feed = Feed.new message: message
        friend.feeds << feed
        friend.save
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters, if: :devise_controller?

  # GET /users/sign_up
  def new
    build_resource({})
    resource.schools.build
    respond_with self.resource
  end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def destroy
    if resource.friendships
      friends = []
      resource.friendships.each do |friendship|
        friends << friendship.friend
      end
      friendships = []
      friends.each do |friend|
        friendships << Friendship.where(user_id: friend.id, friend_id: resource.id).first
        friendships << Friendship.where(user_id: resource.id, friend_id: friend.id).first
      end

      if resource.destroy
        friendships.each do |f|
          f.destroy
        end
      end
    else
      resource.destroy
    end
    
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u|
      u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar, schools_attributes: [:id, :name, :_destroy])
    }
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar,  :current_password, schools_attributes: [:id, :name, :_destroy] )
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def my_profile
    search_path params[:search] if params[:search]
    @user = User.find(current_user.id)
    @feeds = @user.feeds.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    @friendships = @user.friendships.order(accepted: :asc).paginate(page: params[:page], per_page: 10)
  end

  def profile
    search_path params[:search] if params[:search]
    @user = User.find(params[:id])
    @friendships = @user.friendships.paginate(page: params[:page], per_page: 10)
  end

  def paginate_feeds
    @feeds = current_user.feeds.paginate(page: params[:page], per_page: 10)
    data = []
    @feeds.each do |feed|
      hash = {}
      hash[:id] = feed.user.id
      hash[:name] = feed.user.full_name
      hash[:message] = feed.message
      data << hash
    end
    respond_to do |format|
      format.json { render json: data }
    end
  end

  def paginate_friends
    @friendships = current_user.friendships.paginate(page: params[:page], per_page: 10)
    data = []
    @friendships.each do |friendship|
      hash = {}
      hash[:id] = friendship.id
      hash[:friend_id] = friendship.friend.id
      hash[:name] = friendship.friend.full_name
      data << hash
    end
    respond_to do |format|
      format.json { render json: data }
    end
  end

  private

    def search_path(search)
      @search = User.search(search).paginate(page: params[:page], per_page: 10)
      render "search"
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_feeds.html.erb
<% @feeds.each do |feed| %>
  <p><%= feed.message %></p>
  <hr>
<% end %>

app/views/users/my_profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <div class="data">
        <h2>Meus dados</h2>
        <%= image_tag @user.avatar(:profile) %>
        <span><%= @user.full_name %></span>

        <div class="user-schools">
          <h2>Escolas em que já lecionou</h2>
          <% @user.schools.each do |school| %>
            <p><%= school.name %></p>
          <% end %>
        </div>
        <div class="user-friends">
          <div class="user-friends-content">
            <h2>Meus amigos</h2>
            <%= render partial: 'shared/friends' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <h2>Minhas Metodologias</h2>
      <%= render partial: 'shared/methodologies' %>
    </div>
    <div class="col-lg-4 feeds">
      <h2>Feeds</h2>
      <div class="feeds-content">
        <%= render partial: 'feeds' %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <div class="data">
        <%= image_tag @user.avatar(:profile) %>
        <span><%= @user.full_name %></span>
        
        <div class="add-friend">
          <% unless @user == current_user %>
            <p><%= link_to "Adicionar amigo", friendships_path(friend_id: @user), class: "btn btn-primary", method: :post if current_user.friendships.where(friend_id: @user).blank? %></p>
          <% end %>
        </div>
      </div>
      <div class="user-schools">
        <h2>Escolas em que já lecionou</h2>
        <% @user.schools.each do |school| %>
          <p><%= school.name %></p>
        <% end %>
      </div>
      <div class="user-friends">
        <div class="friends-content">
          <h2>Meus amigos</h2>
          <%= render partial: 'shared/friends' %>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <h2>Minhas Metodologias</h2>
      <%= render partial: 'shared/methodologies' %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="container">
  <div class="row">
    <% if @search.present? %>
      <% @search.each do |result| %>
        <div class="col-lg-1">
            <%= image_tag result.user.avatar(:search_thumb) %>
        </div>
        <div class="col-lg-11">
          <%= link_to "#{result.title}", methodology_path(result) %> by 
          <%= link_to "#{result.user.full_name}", profile_path(result.user.id) %> - 
          <%= rating_for result, "qualidade", star: 5 %>
          <%= "#{result.teaser}" %>
          <hr/>
        </div>
      <% end %>
    <% else %>
      Nenhum resultado.
    <% end %>
    <%= will_paginate @search, next_label: 'Próximo', previous_label: 'Anterior' %>
  </div>
</div>